### ISSUE TITLE
Need to add fps 30 support and extract subtitle from video track's title clip

### ISSUE THREAD

**Issue by ILG2021** [LoveinYuu/DaVinciResolve_Subtitle-2-SRT#1]

**Comment by LoveinYuu** [comment]
Okay，i`ll take a new method to improve it.

**Comment by LoveinYuu** [comment]
try version 1.3, and i added a english version

**Comment by LoveinYuu** [comment]
And DaVinci api can't get the text on the video track, only "text" will be displayed.

**Comment by ILG2021** [comment]
Thank you, I will have a try.
